[build]
builder = "DOCKERFILE"
dockerfilePath = "coordinator/Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
